### ISSUE TITLE
LexisPlotR package v0.3.2

### ISSUE THREAD

**Issue by Catherine-C** [ottlngr/LexisPlotR#1]
I cannot manage to install the latest version of LexisPlotR (v0.3.2) by using install_github() from the devtools-package.

I wrote the followig code:
devtools::install_github("ottlngr/LexisPlotR")

I received this error message:
Installation failed: SSL certificate problem: unable to get local issuer certificate

Do you have any suggestion?

Thanks in advance.

**Comment by ottlngr** [comment]
Hey @Catherine-C,

thanks for your message. I cannot reproduce this error - so I assume that there is no issue with `LexisPlotR`. Have you tried solving this problem following the instructions here? https://github.com/jeroen/curl/issues/122

**Comment by Catherine-C** [comment]
Thanks a lot for your quick response.
I will try again.

Have a nice day,
Catherine

2017-10-31 11:39 GMT+01:00 Philipp Ottolinger <notifications@github.com>:
